title: Dennis Research Note
description: Security research blog
lang: ko-KR
timezone: Asia/Seoul

url: "https://dennisresearchnote.github.io"
baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /post/:categories/:title/